import { HStack, Button } from '@chakra-ui/react'
import CoursePresentation from '../../components/templates/CoursePresentation'
import AccordionNotes from '../../components/templates/AccordionNotes'
import Timeline from '../../components/templates/Timeline'
import Nemotecnia from '../../components/templates/Nemotecnia'
import type { StudyElement, StudyMnemonicContent } from '../../services/types'
import type { ResourceProgressData } from '../../services/resourceProgress'

interface StudyStageProps {
  title: string
  attemptId: string | null
  resourceId: string | null
  elements: StudyElement[]
  index: number
  studyItemCompleted: boolean
  isSavingMnemonic: boolean
  mnemonicAuto: string
  mnemonicDraft: string
  nextStageAfterStudy: 'quiz' | 'lines' | 'group_sort' | 'find_the_match' | 'open_box' | 'anagram' | 'debate' | 'summary'
  onAutoGenerated: (text: string) => void
  onDraftChange: (text: string) => void
  onSaveProgress: (payload: Partial<ResourceProgressData>) => void
  onSetIndex: (nextIndex: number) => void
  onSetCompleted: (value: boolean) => void
  onGoStage: (stage: 'mnemonic_practice' | 'quiz' | 'lines' | 'group_sort' | 'find_the_match' | 'open_box' | 'anagram' | 'debate' | 'summary') => void
  onPersistMnemonic: (content: StudyMnemonicContent, auto: string, draft: string) => Promise<void>
}

export default function StudyStage({ title, attemptId, resourceId, elements, index, studyItemCompleted, isSavingMnemonic, mnemonicAuto, mnemonicDraft, nextStageAfterStudy, onAutoGenerated, onDraftChange, onSaveProgress, onSetIndex, onSetCompleted, onGoStage, onPersistMnemonic }: StudyStageProps) {
  const el = elements[index]
  if (!el) return null

  if (el.type === 'course_presentation') {
    return (
      <>
        <CoursePresentation key={`cp-${attemptId ?? 'noattempt'}-${resourceId ?? 'nores'}-${index}`} title={title} content={el.content} onCompleted={() => {
          onSetCompleted(true)
          onSaveProgress({ stage: 'study', studyIndex: index, studyItemCompleted: true })
        }} />
        <HStack mt={4} justify="flex-end">
          <Button colorScheme="blue" isDisabled={!studyItemCompleted} onClick={() => {
            const next = index + 1
            onSetCompleted(false)
            if (next < elements.length) {
              onSetIndex(next)
              onSaveProgress({ stage: 'study', studyIndex: next, studyItemCompleted: false, coursePresentationConfirmed: true })
            } else {
              onGoStage(nextStageAfterStudy)
              onSaveProgress({ stage: nextStageAfterStudy, coursePresentationConfirmed: true })
            }
          }}>Continuar</Button>
        </HStack>
      </>
    )
  }

  if (el.type === 'accordion_notes') {
    return (
      <>
        <AccordionNotes key={`an-${attemptId ?? 'noattempt'}-${resourceId ?? 'nores'}-${index}`} title={title} content={el.content} persistKey={`res-${resourceId ?? 'nores'}-att-${attemptId ?? 'noattempt'}-study-${index}`} onCompleted={() => {
          onSetCompleted(true)
          onSaveProgress({ stage: 'study', studyIndex: index, studyItemCompleted: true })
        }} />
        <HStack mt={4} justify="flex-end">
          <Button colorScheme="blue" isDisabled={!studyItemCompleted} onClick={() => {
            const next = index + 1
            onSetCompleted(false)
            if (next < elements.length) {
              onSetIndex(next)
              onSaveProgress({ stage: 'study', studyIndex: next, studyItemCompleted: false, accordionNotesConfirmed: true })
            } else {
              onGoStage(nextStageAfterStudy)
              onSaveProgress({ stage: nextStageAfterStudy, accordionNotesConfirmed: true })
            }
          }}>Continuar</Button>
        </HStack>
      </>
    )
  }

  if (el.type === 'timeline') {
    return (
      <>
        <Timeline key={`tl-${attemptId ?? 'noattempt'}-${resourceId ?? 'nores'}-${index}`} title={title} content={el.content} resourceId={resourceId ?? undefined} onCompleted={() => {
          onSetCompleted(true)
          onSaveProgress({ stage: 'study', studyIndex: index, studyItemCompleted: true })
        }} />
        <HStack mt={4} justify="flex-end">
          <Button colorScheme="blue" isDisabled={!studyItemCompleted} onClick={() => {
            const next = index + 1
            onSetCompleted(false)
            if (next < elements.length) {
              onSetIndex(next)
              onSaveProgress({ stage: 'study', studyIndex: next, studyItemCompleted: false, timelineConfirmed: true })
            } else {
              onGoStage(nextStageAfterStudy)
              onSaveProgress({ stage: nextStageAfterStudy, timelineConfirmed: true })
            }
          }}>Continuar</Button>
        </HStack>
      </>
    )
  }

  if (el.type === 'mnemonic_creator') {
    return (
      <>
        <Nemotecnia key={`mn-${attemptId ?? 'noattempt'}-${resourceId ?? 'nores'}-${index}`} title={title} content={el.content as StudyMnemonicContent} onAutoGenerated={onAutoGenerated} onDraftChange={onDraftChange} onCompleted={() => {
          onSetCompleted(true)
          onSaveProgress({ stage: 'study', studyIndex: index, studyItemCompleted: true })
        }} />
        <HStack mt={4} justify="flex-end">
          <Button colorScheme="blue" isDisabled={!studyItemCompleted} isLoading={isSavingMnemonic} onClick={async () => {
            await onPersistMnemonic(el.content as StudyMnemonicContent, mnemonicAuto, mnemonicDraft)
            onSetCompleted(false)
            onGoStage('mnemonic_practice')
            onSaveProgress({ stage: 'mnemonic_practice', mnemonicCreatorConfirmed: true })
          }}>Continuar</Button>
        </HStack>
      </>
    )
  }

  return null
}
