import React, { useState } from 'react'
import { Box, VStack, HStack, Text, Textarea, Card, CardBody, Alert, AlertIcon, useColorModeValue } from '@chakra-ui/react'
import type { StudyMnemonicContent } from '../../services/types'

interface NemotecniaProps {
  title: string
  content: StudyMnemonicContent
  onAutoGenerated?: (text: string) => void
  onDraftChange?: (text: string) => void
  onCompleted?: () => void // se usa para marcar como completado en el Dashboard (no guardar aquí)
}

/**
 * Componente de creación de mnemotecnia.
 * - Muestra 4 conceptos/preguntas con sus respuestas.
 * - Explica brevemente qué es la mnemotecnia y da un ejemplo.
 * - Permite al alumno escribir su propia mnemotecnia.
 * - Botón "Generar" para que el sistema sugiera una mnemotecnia automática.
 * Nota: El guardado en BD se realiza al presionar "Continuar" en el Dashboard.
 */
export default function Nemotecnia({ content, onDraftChange, onCompleted }: NemotecniaProps) {
  const [draft, setDraft] = useState<string>('')
  const [error] = useState<string | null>(null)
  const cardBg = useColorModeValue('white', 'gray.800')
  const borderColor = useColorModeValue('gray.200', 'gray.700')


  const handleDraftChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const val = e.target.value
    setDraft(val)
    onDraftChange?.(val)
    // Si el alumno escribe algo, considerar la actividad como completada
    if (val.trim().length > 0) {
      onCompleted?.()
    }
  }

  return (
    <Card bg={cardBg} shadow="sm" borderWidth="1px" borderColor={borderColor}>
      <CardBody>
        <VStack align="stretch" spacing={4}>
          <Text fontSize="xl" fontWeight="bold">Crea tu mnemotecnia</Text>
          {content.instructions ? (
            <Text fontSize="sm" color="gray.700">{content.instructions}</Text>
          ) : (
            <Text fontSize="sm" color="gray.700">
              Una mnemotecnia es una frase, acrónimo o historia breve que te ayuda a recordar información.
              Por ejemplo: para recordar los planetas cercanos al Sol podrías usar "Me Ve Tierra Marte" (Mercurio, Venus, Tierra y Marte).
            </Text>
          )}

          {content.exampleText && (
            <Alert status="info" borderRadius="md">
              <AlertIcon />
              <Text fontSize="sm">Ejemplo: {content.exampleText}</Text>
            </Alert>
          )}

          <Box>
            <Text fontSize="md" fontWeight="semibold" mb={2}>Definiciones y respuestas</Text>
            <VStack align="stretch" spacing={2}>
              {content.items.map((it, idx) => (
                <Box key={`mn-${idx}`} p={3} borderWidth="1px" borderRadius="md" borderColor={borderColor}>
                  <Text fontSize="sm" color="gray.700"><strong>{idx + 1}.</strong> Definición: {it.answer}</Text>
                  <Text fontSize="sm" fontWeight="semibold">Respuesta: {it.prompt}</Text>
                </Box>
              ))}
            </VStack>
          </Box>

          <VStack align="stretch" spacing={2}>
            <Text fontSize="md" fontWeight="semibold">Escribe tu mnemotecnia</Text>
            <Textarea placeholder="Escribe aquí tu mnemotecnia (acróstico, frase, historia corta, etc.)" value={draft} onChange={handleDraftChange} rows={4} />
          </VStack>

          <HStack />


          {error && (
            <Alert status="error" borderRadius="md">
              <AlertIcon />
              <Text fontSize="sm">{error}</Text>
            </Alert>
          )}

          {/* Botón de "Marcar como leído" retirado según solicitud */}
        </VStack>
      </CardBody>
    </Card>
  )
}
